grafana:
  testFramework:
    enabled: false
  persistence:
    enabled: true
    type: pvc
    accessModes:
      - ReadWriteOnce
    size: 4Gi
    finalizers:
      - kubernetes.io/pvc-protection
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://kube-prometheus-stack-prometheus:9090
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      nginx:
        url: https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/main/grafana/NGINXPlusICDashboard.json
        datasource: Prometheus
      bigip:
        url: https://raw.githubusercontent.com/f5devcentral/overwatch/refs/heads/main/dashboards/BigIP-TS.json
        datasource: Prometheus
      f5ts:
        json: |
          { 
            key: "value"
          }
prometheus:
  pushgateway:
    enabled: true
  persistentVolume:
    enabled: true
    mountPath: /prometheus
    size: 50gi
    storageClass: managed-csi
    pvcDeleteOnStsDelete: false
    pvcDeleteOnStsScale: false
    existingClaim: grafanadata
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'integrations/f5-bigip'  # Name of the scrape job
        scheme: https  # Use HTTPS for the scrape
        tls_config:
          insecure_skip_verify: true  # Skip TLS certificate verification
        metrics_path: /mgmt/shared/telemetry/pullconsumer/metrics  # Specify the metric path
        static_configs:
          - targets:
            - '10.225.1.101:443'  # Replace with your endpoint hostname and port
            - '10.225.1.102:443'  # Replace with your endpoint hostname and port
        basic_auth:
          username: 'azops'  # Replace with your username
          password: 'Canada12345!'  # Replace with your password
alertmanager:
  enabled: true
  persistence:
    size: 10Gi
prometheus-node-exporter:
  enabled: true
  rbac:
    pspEnabled: false
  containerSecurityContext:
    allowPrivilegeEscalation: false

