apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring
  project: {{ .Values.spec.project }}
  source:
    chart: grafana
    helm:
      parameters:
        - name: "service.type"
          value: "NodePort"
        - name: "service.nodePort"
          value: "32517"
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.31.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
