apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring
  project: {{ .Values.spec.project }}
  source:
    chart: prometheus
    helm:
      parameters:
        - name: "pushgateway.enabled"
          value: "false"
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 15.10.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
