apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana
  labels:
    component: elk
    role: kibana
spec:
  replicas: 1
  elasticsearchRef:
    name: elastic
  selector:
    component: elk
    role: kibana
  template:
    metadata:
      labels:
        component: elk
        role: kibana
    spec:
      serviceAccount: elk
      containers:
      - name: kibana
        image: kibana
        env:
        - name: KIBANA_ES_URL
          value: "http://10.0.148.179:9200/"
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP