apiVersion: v1
kind: ReplicationController
metadata:
  name: logstash
  
  labels:
    component: elk
    role: logstash
spec:
  replicas: 2
  selector:
    component: elk
    role: logstash
  template:
    metadata:
      labels:
        component: elk
        role: logstash
    spec:
      serviceAccount: elk
      containers:
      - name: logstash
        image: elkdemo-microsoft.azurecr.io/elkdemo:1.0
        env:
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        ports:
        - containerPort: 5000
          name: log4js
          protocol: TCP
        volumeMounts:
        - mountPath: /certs
          name: certs
      volumes:
      - emptyDir:
          medium: ""
        name: "storage"
      - hostPath:
          path: "/tmp"
        name: "certs"
      imagePullSecrets:
      - name: dockerreg-secret