{
 "title": "Telemetry Streaming StatsD Dashboard for F5 BIG-IP",
 "description": "Dashboard for the F5 BIG-IP Telemetry Streaming, StatsD.",
 "tags": [
  "BIG-IP ",
  "TS",
  "Telemetry",
  "StatsD",
  "Graphite"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "graphite" },
   { "name": "Device", "query": "stats.gauges.f5telemetry.*" },
   {
    "name": "Tenant",
    "query": "stats.gauges.f5telemetry.$Device.*.*"
   },
   {
    "name": "Application",
    "query": "stats.gauges.f5telemetry.$Device.virtualServers.*"
   },
   {
    "name": "VirtualServer",
    "query": "stats.gauges.f5telemetry.$Device.virtualServers.*"
   },
   {
    "name": "Pool",
    "query": "stats.gauges.f5telemetry.$Device.pools.*"
   },
   {
    "name": "Profile",
    "query": "stats.gauges.f5telemetry.$Device.*Profiles.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Application Health Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Profile 5xx Responses",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "target": "aliasByNode(summarize(nonNegativeDerivative(stats.gauges.f5telemetry.$Device.httpProfiles.*.5xxResp), '2min'), 5)"
      }
     ]
    },
    {
     "title": "HTTP Profile 4xx Responses",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "target": "aliasByNode(summarize(nonNegativeDerivative(stats.gauges.f5telemetry.$Device.*.*.4xxResp), '2min'), 5)"
      }
     ]
    }
   ]
  },
  {
   "title": "Device System Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "BIG-IP Device CPU",
     "type": "graph",
     "description": "The internal system and tmm cpu usage",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(stats.gauges.f5telemetry.$Device.system.cpu, 3, 5)"
      },
      {
       "target": "aliasByNode(stats.gauges.f5telemetry.$Device.system.tmmCpu, 3, 5)"
      }
     ]
    },
    {
     "title": "BIG-IP Device Memory",
     "type": "graph",
     "description": "The internal system and tmm memory usage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(stats.gauges.f5telemetry.$Device.system.memory, 3, 5)"
      },
      {
       "target": "aliasByNode(stats.gauges.f5telemetry.$Device.system.tmmMemory, 3, 5)"
      }
     ]
    },
    {
     "title": "TTM Clientside Traffic In",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(derivative(keepLastValue(stats.gauges.f5telemetry.$Device.system.tmmTraffic.clientSideTraffic-bitsIn)), 3)"
      }
     ]
    },
    {
     "title": "TTM Clientside Traffic Out",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(derivative(keepLastValue(stats.gauges.f5telemetry.$Device.system.tmmTraffic.clientSideTraffic-bitsOut)), 3)"
      }
     ]
    },
    {
     "title": "TTM Serverside Traffic In",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(derivative(keepLastValue(stats.gauges.f5telemetry.$Device.system.tmmTraffic.serverSideTraffic-bitsIn)), 3)"
      }
     ]
    },
    {
     "title": "TTM Serverside Traffic Out",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(derivative(keepLastValue(stats.gauges.f5telemetry.$Device.system.tmmTraffic.serverSideTraffic-bitsOut)), 3)"
      }
     ]
    },
    {
     "title": "Mgmt Interface Traffic In",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(derivative(keepLastValue(stats.gauges.f5telemetry.$Device.system.networkInterfaces.mgmt.counters-bitsIn)), 3)"
      }
     ]
    },
    {
     "title": "Mgmt Interface Traffic Out",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(derivative(keepLastValue(stats.gauges.f5telemetry.$Device.system.networkInterfaces.mgmt.counters-bitsOut)), 3)"
      }
     ]
    },
    {
     "title": "1-0 Interface Traffic In",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(derivative(keepLastValue(stats.gauges.f5telemetry.$Device.system.networkInterfaces.1-0.counters-bitsIn)), 3)"
      }
     ]
    },
    {
     "title": "1-0 Interface Traffic Out",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(derivative(keepLastValue(stats.gauges.f5telemetry.$Device.system.networkInterfaces.1-0.counters-bitsOut)), 3)"
      }
     ]
    }
   ]
  },
  {
   "title": "Virtual Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Virtual Server Client Traffic In",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(derivative(keepLastValue(stats.gauges.f5telemetry.$Device.virtualServers.-$Tenant-$Application-$VirtualServer.clientside-bitsIn)), 5)"
      }
     ]
    },
    {
     "title": "Virtual Server Client Traffic Out",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(derivative(keepLastValue(stats.gauges.f5telemetry.$Device.virtualServers.-$Tenant-$Application-$VirtualServer.clientside-bitsOut)), 5)"
      }
     ]
    },
    {
     "title": "Virtual Server Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(keepLastValue(stats.gauges.f5telemetry.$Device.virtualServers.-$Tenant-$Application-$VirtualServer.clientside-curConns)), 5)"
      }
     ]
    }
   ]
  },
  {
   "title": "Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pool Traffic In",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(keepLastValue(stats.gauges.f5telemetry.$Device.pools.-$Tenant-$Application-$Pool.serverside-bitsIn)), 5)"
      }
     ]
    },
    {
     "title": "Pool Traffic Out",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(keepLastValue(stats.gauges.f5telemetry.$Device.pools.-$Tenant-$Application-$Pool.serverside-bitsOut)), 5)"
      }
     ]
    },
    {
     "title": "Pool Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(keepLastValue(stats.gauges.f5telemetry.$Device.pools.-$Tenant-$Application-$Pool.serverside-curConns)), 5)"
      }
     ]
    }
   ]
  },
  {
   "title": "Pool Members",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pool Member Traffic In",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(keepLastValue(stats.gauges.f5telemetry.$Device.pools.-$Tenant-$Application-$Pool.members.-$Tenant-*.serverside-bitsIn)), 7)"
      }
     ]
    },
    {
     "title": "Pool Member Traffic Out",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(keepLastValue(stats.gauges.f5telemetry.$Device.pools.-$Tenant-$Application-$Pool.members.-$Tenant-*.serverside-bitsOut)), 7)"
      }
     ]
    },
    {
     "title": "Pool Member Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(keepLastValue(stats.gauges.f5telemetry.$Device.pools.-$Tenant-$Application-$Pool.members.-$Tenant-*.serverside-curConns)), 7)"
      }
     ]
    }
   ]
  },
  {
   "title": "Profiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Profile Details",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(keepLastValue(stats.gauges.f5telemetry.$Device.httpProfiles.-$Profile.*)), 6)"
      }
     ]
    },
    {
     "title": "ClientSSL Profile Details",
     "type": "graph",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(keepLastValue(stats.gauges.f5telemetry.$Device.clientSslProfiles.-$Profile.*)), 6)"
      }
     ]
    },
    {
     "title": "ServerSSL Profile Details",
     "type": "graph",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(keepLastValue(stats.gauges.f5telemetry.$Device.serverSslProfiles.-$Profile.*)), 6)"
      }
     ]
    }
   ]
  }
 ]
}