{
 "title": "Telemetry Streaming Dashboard for F5 BIG-IP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": {
     "query": "label_values(f5_system_cpu{},instance)"
    }
   },
   {
    "name": "VirtualServer",
    "query": {
     "query": "label_values(f5_totRequests{instance=~\"$Device:.*\"},virtualServers)"
    }
   },
   {
    "name": "Pool",
    "query": {
     "query": "label_values(f5_totRequests{instance=~\"$Device:.*\"},pools)"
    }
   },
   {
    "name": "httpProfile",
    "query": {
     "query": "label_values(f5_getReqs{instance=~\"$Device:.*\"},httpProfiles)"
    }
   },
   {
    "name": "clientSslProfile",
    "query": {
     "query": "label_values(f5_currentConnections{instance=~\"$Device:.*\"},clientSslProfiles)"
    }
   },
   {
    "name": "serverSslProfile",
    "query": {
     "query": "label_values(f5_currentConnections{instance=~\"$Device:.*\"},serverSslProfiles)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Application Health Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Profile 2xx Responses",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(f5_2xxResp{instance=~\"$Device:.*\"})"
    }
   ]
  },
  {
   "title": "HTTP Profile 3xx Responses",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(f5_3xxResp{instance=~\"$Device:.*\"})"
    }
   ]
  },
  {
   "title": "HTTP Profile 4xx Responses",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(f5_4xxResp{instance=~\"$Device:.*\"})"
    }
   ]
  },
  {
   "title": "HTTP Profile 5xx Responses",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(f5_5xxResp{instance=~\"$Device:.*\"})"
    }
   ]
  },
  {
   "title": "HTTP Profile 4xx Responses",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "f5_4xxResp{instance=~\"$Device:.*\"} > 100"
    }
   ]
  },
  {
   "title": "HTTP Profile 5xx Responses",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "f5_5xxResp{instance=~\"$Device:.*\"} > 100"
    }
   ]
  },
  {
   "title": "HTTP Profile fatal Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "f5_fatalAlerts{instance=~\"$Device:.*\"} > 100"
    }
   ]
  },
  {
   "title": "sslCerts Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "f5_expirationDate" }
   ]
  },
  {
   "title": "Response Greater Than 2m",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "f5_respGreaterThan2m{instance=~\"$Device:.*\"} > 0"
    }
   ]
  },
  { "title": "Device System Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "BIG-IP Device CPU",
   "type": "timeseries",
   "description": "The internal system and tmm cpu usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_system_cpu{instance=~\"$Device:.*\"}",
     "legendFormat": "$Device-CPU"
    },
    {
     "expr": "f5_system_tmmCpu{instance=~\"$Device:.*\"}",
     "legendFormat": "$Device-TmmCPU"
    }
   ]
  },
  {
   "title": "BIG-IP Device Memory",
   "type": "timeseries",
   "description": "The internal system and tmm memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_system_memory{instance=~\"$Device:.*\"}",
     "legendFormat": "$Device-Memory"
    },
    {
     "expr": "f5_system_tmmMemory{instance=~\"$Device:.*\"}",
     "legendFormat": "$Device-tmmMemory"
    }
   ]
  },
  {
   "title": "F5 Disk Storage Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_Capacity_Float{instance=~\"$Device:.*\"} > 0",
     "legendFormat": "{{diskStorage}}"
    }
   ]
  },
  {
   "title": "F5 disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "f5_r_s{instance=~\"$Device:.*\"} > 0",
     "legendFormat": "$Device - Read - {{diskLatency}}"
    },
    {
     "expr": "- f5_w_s{instance=~\"$Device:.*\"} < 0",
     "legendFormat": "$Device - Write -{{diskLatency}}"
    }
   ]
  },
  {
   "title": "TTM Clientside Traffic In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "deriv(f5_system_tmmTraffic_clientSideTraffic_bitsIn{instance=~\"$Device:.*\"}[5m])",
     "legendFormat": "$Device-clientSideTraffic_bitsIn"
    }
   ]
  },
  {
   "title": "TTM Clientside Traffic Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(f5_system_tmmTraffic_clientSideTraffic_bitsOut{instance=~\"$Device:.*\"}[5m])",
     "legendFormat": "$Device-clientTraffic_bitsOut"
    }
   ]
  },
  {
   "title": "TTM Serverside Traffic In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "deriv(f5_system_tmmTraffic_serverSideTraffic_bitsIn{instance=~\"$Device:.*\"}[5m])",
     "legendFormat": "$Device-serverSideTraffic_bitsIn"
    }
   ]
  },
  {
   "title": "TTM Serverside Traffic Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(f5_system_tmmTraffic_serverSideTraffic_bitsOut{instance=~\"$Device:.*\"}[5m])",
     "legendFormat": "$Device-serverSideTraffic_bitsOut"
    }
   ]
  },
  {
   "title": "Mgmt Interface Traffic In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(f5_counters_bitsIn{instance=~\"$Device:.*\",networkInterfaces=\"mgmt\"}[5m])",
     "legendFormat": "$Device"
    }
   ]
  },
  {
   "title": "Mgmt Interface Traffic Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(f5_counters_bitsOut{instance=~\"$Device:.*\",networkInterfaces=\"mgmt\"}[5m])",
     "legendFormat": "$Device"
    }
   ]
  },
  {
   "title": "X-0 Interface Traffic In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(f5_counters_bitsOut{instance=~\"$Device:.*\",networkInterfaces=~\".*0\"}[5m])",
     "legendFormat": "$Device-{{networkInterfaces}}"
    }
   ]
  },
  {
   "title": "X-0 Interface Traffic Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(f5_counters_bitsIn{instance=~\"$Device:.*\",networkInterfaces=~\".*0\"}[5m])",
     "legendFormat": "$Device-{{networkInterfaces}}"
    }
   ]
  },
  { "title": "Virtual Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Virtual Server Client Traffic In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(f5_clientside_bitsIn{instance=~\"$Device:.*\",virtualServers='$VirtualServer'}[5m])",
     "legendFormat": "$VirtualServer"
    }
   ]
  },
  {
   "title": "Virtual Server Client Traffic Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(f5_clientside_bitsOut{instance=~\"$Device:.*\",virtualServers='$VirtualServer'}[5m])",
     "legendFormat": "$VirtualServer"
    }
   ]
  },
  {
   "title": "Virtual Server Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(f5_clientside_curConns{instance=~\"$Device:.*\",virtualServers='$VirtualServer'}[5m])",
     "legendFormat": "$VirtualServer"
    }
   ]
  },
  { "title": "Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Pool Traffic In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(f5_serverside_bitsIn{instance=~\"$Device:.*\",pools=\"$Pool\",members=\"\"}[5m])",
     "legendFormat": "$Device-$Pool"
    }
   ]
  },
  {
   "title": "Pool Traffic Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(f5_serverside_bitsOut{instance=~\"$Device:.*\",pools=\"$Pool\",members=\"\"}[5m])",
     "legendFormat": "$Device-$Pool"
    }
   ]
  },
  {
   "title": "Pool Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f5_serverside_bitsOut{instance=~\"$Device:.*\",pools=\"$Pool\",members=\"\"}",
     "legendFormat": "$Device-$Pool"
    }
   ]
  },
  { "title": "Pool Member", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Pool Member Traffic In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_serverside_bitsIn{instance=~\"$Device:.*\",pools=\"$Pool\",members!=\"\"}",
     "legendFormat": "$Device - $Pool - {{members}}"
    }
   ]
  },
  {
   "title": "Pool Member Traffic Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(f5_serverside_bitsOut{instance=~\"$Device:.*\",pools=\"$Pool\",members!=\"\"}[5m])",
     "legendFormat": "$Device - $Pool - {{members}}"
    }
   ]
  },
  {
   "title": "Pool Member Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_serverside_curConns{instance=~\"$Device:.*\",pools=\"$Pool\",members!=\"\"}"
    }
   ]
  },
  { "title": "HTTP Profiles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "HTTP Profile Details",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_numberReqs{instance=~\"$Device:.*\",httpProfiles=\"$httpProfile\"}",
     "legendFormat": "$httpProfile"
    }
   ]
  },
  {
   "title": "HTTP Keepalive Request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_maxKeepaliveReq{instance=~\"$Device:.*\",httpProfiles=\"$httpProfile\"}",
     "legendFormat": "$httpProfile"
    }
   ]
  },
  {
   "title": "HTTP Get Request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_getReqs{instance=~\"$Device:.*\",httpProfiles=\"$httpProfile\"}",
     "legendFormat": "$httpProfile"
    }
   ]
  },
  {
   "title": "HTTP Post Request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_postReqs{instance=~\"$Device:.*\",httpProfiles=\"$httpProfile\"}",
     "legendFormat": "$httpProfile"
    }
   ]
  },
  { "title": "SSL Profiles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "ClientSSL Profile active Hand shake Rejected",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_activeHandshakeRejected{instance=~\"$Device:.*\",clientSslProfiles=\"$clientSslProfile\"}",
     "legendFormat": "$clientSslProfile"
    }
   ]
  },
  {
   "title": "ClientSSL Profile current Active Hand shakes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_currentActiveHandshakes{instance=~\"$Device:.*\",clientSslProfiles=\"$clientSslProfile\"}",
     "legendFormat": "$clientSslProfile"
    }
   ]
  },
  {
   "title": "ClientSSL Profile current Compatible Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_currentCompatibleConnections{instance=~\"$Device:.*\",clientSslProfiles=\"$clientSslProfile\"}",
     "legendFormat": "$clientSslProfile"
    }
   ]
  },
  {
   "title": "ClientSSL Profile  current Native Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_currentNativeConnections{instance=~\"$Device:.*\",clientSslProfiles=\"$clientSslProfile\"}",
     "legendFormat": "$clientSslProfile"
    }
   ]
  },
  {
   "title": "ClientSSL Profile Current Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_currentConnections{instance=~\"$Device:.*\",clientSslProfiles=\"$clientSslProfile\"}",
     "legendFormat": "$clientSslProfile"
    }
   ]
  },
  {
   "title": "ClientSSL Profile fatal Alerts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_fatalAlerts{instance=~\"$Device:.*\",clientSslProfiles=\"$clientSslProfile\"}",
     "legendFormat": "$clientSslProfile"
    }
   ]
  },
  {
   "title": "ServerSSL Profile Details",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_currentConnections{instance=~\"$Device:.*\",serverSslProfiles=\"$serverSslProfile\"}",
     "legendFormat": "$serverSslProfile"
    }
   ]
  }
 ]
}