grafana:
  testFramework:
    enabled: false
  persistence:
    enabled: true
    type: pvc
    accessModes:
      - ReadWriteOnce
    size: 50gi
    storageClassName: managed-csi
    finalizers:
      - kubernetes.io/pvc-protection
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://grafana-labs-stack-kube-pr-prometheus:9090
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      nginx:
        url: https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/main/grafana/NGINXPlusICDashboard.json
        datasource: Prometheus
      bigip:
        url: https://raw.githubusercontent.com/f5devcentral/overwatch/refs/heads/main/dashboards/BigIP-TS.json
        datasource: Prometheus
      f5bigip:
        url: https://raw.githubusercontent.com/f5devcentral/overwatch/refs/heads/main/dashboards/TS.json
        datasource: Prometheus
      f5cis: 
prometheus:
  pushgateway:
    enabled: true
  persistentVolume:
    enabled: true
    mountPath: /prometheus
    size: 50gi
    storageClass: managed-csi
    pvcDeleteOnStsDelete: false
    pvcDeleteOnStsScale: false
    existingClaim: prometheus-data
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'integrations/f5-bigip'  # Name of the scrape job
        scheme: https  # Use HTTPS for the scrape
        scrape_timeout: 30s
        scrape_interval: 60s
        tls_config:
          insecure_skip_verify: true  # Skip TLS certificate verification
        metrics_path: /mgmt/shared/telemetry/pullconsumer/metrics  # Specify the metric path
        static_configs:
          - targets:
            - '10.127.254.5:443'  # Replace with your endpoint hostname and port
            - '10.127.254.6:443'  # Replace with your endpoint hostname and port
        basic_auth:
          username: 'azops'  # Replace with your username
          password: 'Canada123456'  # Replace with your password
      - job_name: cis
        scrape_interval: 10s
        metrics_path: '/metrics'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: k8s_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: k8s_pod_name
          - source_labels: [__address__]
            action: replace
            regex: ([^:]+)(?::\d+)?
            replacement: ${1}:8080
            target_label: __address__
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: k8s-bigip-ctlr
alertmanager:
  enabled: true
  persistence:
    enabled: true
    type: pvc
    accessModes:
      - ReadWriteOnce
    size: 10gi
    storageClassName: managed-csi
    finalizers:
      - kubernetes.io/pvc-protection
prometheus-node-exporter:
  enabled: true
  rbac:
    pspEnabled: false
  containerSecurityContext:
    allowPrivilegeEscalation: false