apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  namespace: default
  name: argocd-ingress-https-vs
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: 10.127.252.11
  virtualServerHTTPPort: 8080
  virtualServerHTTPSPort: 8443
  virtualServerName: argocd-ingress-https-vs
  snat: auto
  allowVlans: ["/Common/external"]
  persistenceProfile: "destination-address"
  profiles:
    tcp:
      client: /Common/f5-tcp-wan
      server: /Common/f5-tcp-lan
  host: argocd.f5demo.com
  httpTraffic: redirect
  pools:
  - path: /
    service: argocd-stack
    servicePort: 80
    reselectTries: 3
    serviceDownAction: reselect
    monitors:
     - interval: 5
       recv: "HTTP"
       send: "HEAD / HTTP/1.0\r\n\r\n"
       timeout: 15
       type: http
  tlsProfileName: argo-terminate-tls13
---
apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: argo-terminate-tls13
  namespace: default
  labels:
    f5cr: "true"
spec:
  tlsCipher:
    tlsVersion: "1.3"
    cipherGroup: /Common/f5-default
  tls:
    termination: edge
    clientSSL: /Common/clientssl
    reference: bigip
  hosts:
  - argocd.f5demo.com
  - argocd.canadacentral.cloudapp.azure.com