apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  namespace: default
  name: grafana-ingress-https-vs
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: 10.127.252.11
  virtualServerHTTPPort: 8080
  virtualServerHTTPSPort: 8443
  virtualServerName: grafana-ingress-https-vs
  snat: auto
  allowVlans: ["/Common/external"]
  persistenceProfile: "destination-address"
  profiles:
    tcp:
      client: /Common/f5-tcp-wan
      server: /Common/f5-tcp-lan
  host: grafana.f5demo.com
  httpTraffic: redirect
  defaultPool:
    reference: service
    service: grafana-labs-stack
    serviceNamespace: default
    loadBalancingMethod: fastest-node
    servicePort: 80
    serviceDownAction: reselect
    reselectTries: 3
    monitors:
     - interval: 5
       recv: a
       send: /
       targetPort: 80
       timeout: 15
       type: tcp
     - interval: 5
       recv: a
       send: /
       timeout: 15
       type: http
     - name: /Common/http
       reference: bigip
  pools:
  - path: /
    service: grafana-labs-stack
    servicePort: 80
    reselectTries: 3
    serviceDownAction: reselect
    monitors:
     - interval: 5
       recv: a
       send: /
       targetPort: 80
       timeout: 15
       type: tcp
     - interval: 5
       recv: a
       send: /
       timeout: 15
       type: http
     - name: /Common/http
       reference: bigip
  tlsProfileName: graf-terminate-tls13
---
apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: graf-terminate-tls13
  namespace: default
  labels:
    f5cr: "true"
spec:
  tlsCipher:
    tlsVersion: "1.3"
    cipherGroup: /Common/f5-default
  tls:
    termination: edge
    clientSSL: /Common/clientssl
    reference: bigip
  hosts:
  - grafana.f5demo.com