apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: grafana-ingress-https-vs
  namespace: default
spec:
  virtualServerAddress: 52.156.22.174
  virtualServerName: grafana-ingress-https-vs
  snat: auto
  allowVlans: ["/Common/external"]
  persistenceProfile: "destination-address"
  profiles:
    tcp:
      client: /Common/f5-tcp-wan
      server: /Common/f5-tcp-lan
  host: grafana.f5demo.com
  httpTraffic: redirect
  pools:
    - monitor:
        interval: 5
        recv: ""
        send: /
        timeout: 15
        type: https
        sslProfile: /Common/serverssl
      path: /bar
      service: grafana-labs-stack
      servicePort: 80
  tlsProfileName: terminate-tls
---
apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: terminate-tls
  labels:
    f5cr: "true"
spec:
  tlsCipher:
    tlsVersion: "1.3"
    cipherGroup: /Common/f5-default
  tls:
    termination: edge
    clientSSL: /Common/clientssl
    reference: bigip
  hosts:
  - grafana.f5demo.com