apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  namespace: elastic-system
  name: kibana-ingress-https-vs
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: 0.0.0.0
  virtualServerHTTPPort: 5600
  virtualServerHTTPSPort: 5601
  virtualServerName: kibana-ingress-https-vs
  snat: auto
  allowVlans: ["/Common/external"]
  persistenceProfile: "destination-address"
  profiles:
    tcp:
      client: /Common/f5-tcp-wan
      server: /Common/f5-tcp-lan
  host: kibana.f5demo.com
  httpTraffic: redirect
  pools:
  - path: /
    service: elk-stack-eck-kibana-kb-http
    servicePort: 5601
    reselectTries: 3
    serviceDownAction: reselect
    monitors:
     - interval: 5
       recv: "HTTP"
       send: "HEAD / HTTP/1.0\r\n\r\n"
       timeout: 15
       type: https
  tlsProfileName: kibana-reencrypt-tls13
---
apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: reencrypt-tls13
  namespace: elastic-system
  labels:
    f5cr: "true"
spec:
  tlsCipher:
    tlsVersion: "1.3"
    cipherGroup: /Common/f5-default
  tls:
    termination: reencrypt
    clientSSL: /Common/clientssl
    serverSSL: /Common/serverssl
    reference: bigip
  hosts:
  - kibana.f5demo.com
  - kibana.canadacentral.cloudapp.azure.com