apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: kibana-ingress-https-vs
  namespace: elastic-system
spec:
  virtualServerAddress: 0.0.0.0/0
  virtualServerName: kibana-ingress-https-vs
  snat: auto
  allowVlans: ["/Common/external"]
  persistenceProfile: "destination-address"
  profiles:
    tcp:
      client: /Common/f5-tcp-wan
      server: /Common/f5-tcp-lan
  host: kibana.f5demo.com
  httpTraffic: redirect
  pools:
    - monitor:
        interval: 5
        recv: ""
        send: /
        timeout: 15
        type: https
        sslProfile: /Common/serverssl
      path: /bar
      service: elk-stack-eck-kibana-kb-http
      servicePort: 5601
  tlsProfileName: reencrypt-tls1.3
---
apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: reencrypt-tls1.3
  namespace: elastic-system
  labels:
    f5cr: "true"
spec:
  tlsCipher:
    tlsVersion: "1.3"
    cipherGroup: /Common/f5-default
  tls:
    termination: reencrypt
    clientSSL: /Common/clientssl
    serverSSL: /Common/serverssl
    reference: bigip
  hosts:
  - kibana.f5demo.com