apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: logstash-ingress-hecs-vs
  namespace: default
spec:
  virtualServerAddress: 52.156.22.174
  virtualServerPort: 7443
  virtualServerName: logstash-ingress-hecs-vs
  mode: standard
  snat: auto
  allowVlans: ["/Common/external"]
  persistenceProfile: "destination-address"
  profiles:
    tcp:
      client: /Common/f5-tcp-wan
      server: /Common/f5-tcp-lan
  host: logstach-hecs.f5demo.com
  pools:
    - monitor:
        interval: 5
        recv: ""
        send: /
        timeout: 15
        type: https
        sslProfile: /Common/serverssl
      path: /bar
      service: svc-3
      servicePort: 7443
      serviceDownAction: reselect
      reselectTries: 3
  tlsProfileName: terminate-tls
---
apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: terminate-tls
  labels:
    f5cr: "true"
spec:
  tlsCipher:
    tlsVersion: "1.3"
    cipherGroup: /Common/f5-default
  tls:
    termination: edge
    clientSSL: /Common/clientssl
    reference: bigip
  hosts:
  - logstach-hecs.f5demo.com