apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  namespace: elastic-system
  name: logstash-ingress-hec-vs
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: 10.127.252.11
  virtualServerHTTPPort: 7080
  virtualServerHTTPSPort: 7443
  virtualServerName: logstash-ingress-hec-vs
  snat: auto
  allowVlans: ["/Common/external"]
  persistenceProfile: "destination-address"
  profiles:
    tcp:
      client: /Common/f5-tcp-wan
      server: /Common/f5-tcp-lan
  host: logstash-hec.f5demo.com
  httpTraffic: allow
  pools:
  - path: /
    service: logstash-ls-beats-ls-hec
    servicePort: 7080
    reselectTries: 3
    serviceDownAction: reselect
    monitors:
     - interval: 5
       recv: "200"
       send: "HEAD / HTTP/1.0\r\n\r\n"
       timeout: 15
       type: http
  tlsProfileName: terminate-tls13
---
apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: terminate-tls13
  labels:
    f5cr: "true"
spec:
  tlsCipher:
    tlsVersion: "1.3"
    cipherGroup: /Common/f5-default
  tls:
    termination: edge
    clientSSL: /Common/clientssl
    reference: bigip
  hosts:
  - logstash-hec.f5demo.com