apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  labels:
    f5cr: "true"
  name: logstash-ingress-beats-vs
  namespace: elastic-system
spec:
  virtualServerAddress: 52.156.22.174
  virtualServerPort: 5044
  virtualServerName: logstash-ingress-beats-vs
  mode: performance
  snat: auto
  allowVlans: ["/Common/external"]
  persistenceProfile: "destination-address"
  profileL4: /Common/security-fastL4
  profiles:
    tcp:
      client: /Common/f5-tcp-wan
      server: /Common/f5-tcp-lan
  pool:
    service: logstash-ls-beats-ls-beats
    servicePort: 5044
    loadBalancingMethod: fastest-node
    monitor:
      type: tcp
      interval: 5
      timeout: 15
    reselectTries: 3
    serviceDownAction: reselect