apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: wildcard-ingress-https-vs
  namespace: default
spec:
  virtualServerAddress: 10.127.252.11
  virtualServerPort: 7514
  virtualServerName: wildcard-ingress-https-vs
  mode: standard
  snat: auto
  allowVlans: ["/Common/external"]
  persistenceProfile: "destination-address"
  profiles:
    tcp:
      client: /Common/f5-tcp-wan
      server: /Common/f5-tcp-lan
  host: kibana.f5demo.com
  pools:
    - monitor:
        interval: 5
        recv: ""
        send: /
        timeout: 15
        type: https
        sslProfile: /Common/serverssl
      path: /bar
      service: svc-3
      servicePort: 80
      reselectTries: 3
      serviceDownAction: reselect  
  tlsProfileName: reencrypt-tls
---
apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: tlscipher-tls1.3
  labels:
    f5cr: "true"
spec:
  tlsCipher:
    tlsVersion: "1.3"
    cipherGroup: /Common/f5-default
  tls:
    termination: reencrypt
    clientSSL: /Common/clientssl
    serverSSL: /Common/serverssl
    reference: bigip
  hosts:
  - *.f5demo.com